<html>
<head>
    <title>Todo List App</title>
    <link href="https://fonts.googleapis.com/css?family=Concert+One|Rubik+Mono+One" rel="stylesheet">
    <link rel='stylesheet' href='styles/styles.css'>
</head>

<body>
    <div class='container'>
        <aside>
            <h1>2 -</h1>
            <h1>D u</h1>
            <h3>THE TO-DO LIST APP</h3>
            <form action='/addTodo' method='post'>
                <input type='text' name='message'>
                <input type='submit' value='submit'>
            </form>
        </aside>
        <main>
            <?php
            foreach ($toDos as $item) {
                echo "
                <div class='todo-item'>
                    <div class='todo-item-header'>To-Do Item</div>
                    <p>" . $item['message'] . "</p>
                    <form action='/completeTodo' method='post'>
                        <input type='hidden' name='id' value='" . $item['id'] . "'/>
                        <input type='submit' value='Complete'>
                    </form>
                </div>";}
            ?>
        </main>
    </div>
</body>
</html>



