<html>
<head>
    <title>Todo List App</title>
    <link rel='stylesheet' href='styles/styles.css'>
</head>

<body>
    <main>
        <h1>TODO List app</h1>
        <?php
        foreach ($toDos as $item) {
            echo "
            <div class='todo-item'>
                <p>Todo: " . $item['message'] . "</p>
                <form action='/completeTodo' method='post'>
                    <input type='hidden' value='" . $item['id'] . "'/>
                    <input type='submit' value='Complete'>
                </form>
            </div>";}
        ?>
        <form action='/addTodo' method='post'>
            <input type='text' name='message'>
            <input type='submit' value='submit'>
        </form>
    </main>
</body>
</html>



